pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri('https://repo.jftechsoft.com/repository/maven-releases/') }
    }
}
rootProject.name = "CFTVLocal"
include(":app")
